image: quay.io/python-devs/ci-image

stages:
  - test
  - codecov
  - deploy

qa:
  script:
    - tox -e qa

tests:
  script:
    - tox -e py36-nocov,py37-nocov

coverage:
  script:
    - tox -e py36-cov,py37-cov
  artifacts:
    paths:
      - coverage.xml

diffcov:
  script:
    - tox -e py36-diffcov,py37-diffcov

docs:
  script:
    - tox -e docs

codecov:
  stage: codecov
  dependencies:
    - coverage
  script:
    - codecov -t $CODECOV_TOKEN
  when: on_success

release:
  variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
  stage: deploy
  only:
    - /^\d+\.\d+(\.\d+)?([abc]\d*)?$/
  script:
    - tox -e release
